dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-fpga.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-2GB-tee.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-3GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-qa-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-bananapi-w2-2GB-HDMI.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
